import { NextRequest, NextResponse } from 'next/server'
import sharp from 'sharp'
import { createClient } from '@supabase/supabase-js'

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url)
  const path = searchParams.get('path')

  if (!path) {
    return NextResponse.json({ error: 'Path manquant' }, { status: 400 })
  }

  const token = req.headers.get('Authorization')?.replace('Bearer ', '')
  if (!token) {
    return NextResponse.json({ error: 'Non authentifié' }, { status: 401 })
  }

  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
    }
  )

  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) {
    return NextResponse.json({ error: 'Utilisateur non connecté' }, { status: 401 })
  }

  const { data: signed } = await supabase.storage
    .from('contents')
    .createSignedUrl(path, 60)

  if (!signed?.signedUrl) {
    return NextResponse.json({ error: 'Fichier non trouvé' }, { status: 404 })
  }

  const response = await fetch(signed.signedUrl)
  const arrayBuffer = await response.arrayBuffer()
  const buffer = Buffer.from(arrayBuffer)

  const username = user.user_metadata?.username || user.email || 'user'
  const trace = user.id.slice(0, 16)

  // Lire la taille originale de l’image
  const originalImage = sharp(buffer)
  const { width = 600 } = await originalImage.metadata()

  // Génère le watermark SVG dynamique
  const watermarkSvg = Buffer.from(`
    <svg width="${width}" height="50">
      <style>
        .text { font-size: 20px; fill: white; font-family: Arial; }
      </style>
      <text x="10" y="35" class="text">@${username} – DZYR</text>
    </svg>
  `)

  // Composite sécurisé
  const watermarked = await originalImage
    .composite([
      {
        input: watermarkSvg,
        top: (await originalImage.metadata()).height! - 50,
        left: 0,
      },
    ])
    .withMetadata({
      exif: {
        IFD0: {
          Copyright: `Generated by DZYR | TraceID:${trace}`,
        },
      },
    })
    .png()
    .toBuffer()

  return new NextResponse(watermarked, {
    status: 200,
    headers: {
      'Content-Type': 'image/png',
      'Cache-Control': 'no-store',
    },
  })
}
